const SILVESTRA_CONTENT = {
  assets: {
    logoColor: 'assets/logo-color-trim.png',
    logoCream: 'assets/logo-cream-trim.png',
    heroImage: './assets/hero.jpg',
  },
  contact: {
    email: 'hola@silvestra.uy',
    instagram: 'https://www.instagram.com/silvestra.paisajismo',
    instagramLabel: '@silvestra.paisajismo',
    phoneLabel: '097 236 903',
    phoneUrl: 'tel:+59897236903',
    whatsapp: 'https://wa.me/59897236903',
  },
  nav: [
    { href: '#filosofia', label: 'Filosofía' },
    { href: '#servicios', label: 'Servicios' },
    { href: '#planos', label: 'Planos' },
    { href: '#portfolio', label: 'Portfolio' },
    { href: '#contacto', label: 'Contacto' },
  ],
  hero: {
    eyebrow: '· Diseño y construcción de jardines ·',
    locations: 'Punta del Este – La Barra – Manantiales – José Ignacio',
    title: 'habitar tu naturaleza',
    text: 'Paisajismo que dialoga con la naturaleza, la estética del diseño y los procesos vivos.',
  },
  filosofia: {
    eyebrow: 'Nuestra filosofía',
    title: 'Lo silvestre también se diseña. Jardines libres, vivos y en equilibrio.',
    accent: 'silvestre',
    text: 'Silvestra surge del deseo de co-crear con la naturaleza. Concebimos jardines que respetan sus ritmos y potencian su esencia, espacios donde la vegetación, la luz y el tiempo dialogan en armonía. Lugares que inspiran libertad, serenidad y una conexión profunda con el mundo vivo que nos contiene.',
    pillars: [
      {
        number: '01',
        title: 'Diseñar con la naturaleza',
        text: 'Trabajamos con los procesos naturales respetando la dinámica propia de cada lugar. Combinamos especies nativas con exóticas no invasoras para crear paisajes que dialogan con el monte costero, las dunas y la laguna.',
      },
      {
        number: '02',
        title: 'Refugio para la vida',
        text: 'Cada jardín es un pequeño ecosistema en movimiento. Atrae polinizadores, ofrece alimento y refugio a las aves y contribuye a fortalecer la biodiversidad local. Más que un espacio ornamental, es un lugar donde la vida encuentra su lugar.',
      },
      {
        number: '03',
        title: 'Sin químicos, con equilibrio',
        text: 'Trabajamos con abonos orgánicos y prácticas respetuosas con el ambiente. Fauna protegida, niños y mascotas seguros. Un jardín sano que se sostiene en el tiempo y madura con las estaciones.',
      },
    ],
  },
  servicios: {
    eyebrow: 'Servicios',
    title: 'Del concepto al jardín que perdura',
    items: [
      {
        number: '01',
        title: 'Consulta inicial',
        text: 'Visita al sitio, diagnóstico y primera valoración para entender el lugar, sus posibilidades y el alcance del proyecto.',
      },
      {
        number: '02',
        title: 'Proyecto completo',
        text: 'Moodboard, memoria descriptiva, planos a escala, detalles constructivos, listado de especies y guía de manejo.',
      },
      {
        number: '03',
        title: 'Ejecución y dirección de obra',
        text: 'Coordinación de equipo y dirección en obra. Hardscape incluido: decks, estanques, fogones y áreas de agua.',
      },
      {
        number: '04',
        title: 'Seguimiento post-instalación',
        text: 'Visitas de puesta a punto durante el primer año para acompañar el arraigo y evolución del jardín.',
      },
    ],
  },
  planos: {
    eyebrow: 'Planos y proceso creativo',
    title: 'Del trazo inicial a una lectura clara del jardín',
    text: 'Antes de construir, traducimos el lugar en capas: recorridos, especies, materialidades y atmósferas. Los planos y representaciones permiten visualizar decisiones y ajustar el proyecto con precisión.',
    images: [
      { src: './assets/planos/alzado-cantero-maritimo.webp', label: 'Alzado cantero marítimo', size: 'medium' },
      { src: './assets/planos/axonometria.webp', label: 'Axonometría', size: 'tall' },
      { src: './assets/planos/cantero-tecnica-mano-alzada.webp', label: 'Cantero, técnica mano alzada', size: 'small' },
      { src: './assets/planos/chacra-vista-area-espejos-de-agua.webp', label: 'Chacra, vista aérea de espejos de agua', size: 'wide' },
      { src: './assets/planos/corte-area-para-teens.webp', label: 'Corte, área para teens', size: 'medium' },
      { src: './assets/planos/corte-lago-y-puente.webp', label: 'Corte, lago y puente', size: 'wide' },
      { src: './assets/planos/corte-tecnica-mano-alzada.webp', label: 'Corte, técnica mano alzada', size: 'small' },
      { src: './assets/planos/corte-y-vista-de-balcon.webp', label: 'Corte y vista de balcón', size: 'medium' },
      { src: './assets/planos/diseno-de-pergola.webp', label: 'Diseño de pérgola', size: 'small' },
      { src: './assets/planos/grafico-aves-por-estaciones-proyecto-en-laguna.webp', label: 'Gráfico de aves por estaciones, proyecto en laguna', size: 'wide' },
      { src: './assets/planos/listado-especies-para-chacra.webp', label: 'Listado de especies para chacra', size: 'tall' },
      { src: './assets/planos/monte-nativo-y-mirador.webp', label: 'Monte nativo y mirador', size: 'medium' },
      { src: './assets/planos/perspectiva-cafe-museo.webp', label: 'Perspectiva, café museo', size: 'small' },
      { src: './assets/planos/perspectiva-patio-museo.webp', label: 'Perspectiva, patio museo', size: 'medium' },
      { src: './assets/planos/plano-de-plantacion.webp', label: 'Plano de plantación', size: 'large' },
      { src: './assets/planos/plano-laguna.webp', label: 'Plano laguna', size: 'medium' },
      { src: './assets/planos/plano-plantacion.webp', label: 'Plano plantación', size: 'small' },
      { src: './assets/planos/plano-reserva.webp', label: 'Plano reserva', size: 'medium' },
      { src: './assets/planos/plano-villa.webp', label: 'Plano villa', size: 'wide' },
      { src: './assets/planos/pradera-intervenida.webp', label: 'Pradera intervenida', size: 'small' },
      { src: './assets/planos/zonificacion-para-chacra.webp', label: 'Zonificación para chacra', size: 'medium' },
    ],
    steps: [
      'Relevamiento del terreno y su entorno.',
      'Moodboard de atmósfera, materialidad y especies.',
      'Planos de implantación, canteros y recorridos.',
      'Representaciones para visualizar escala y experiencia.',
    ],
  },
  portfolio: {
    eyebrow: 'Portfolio',
    title: 'Texturas de jardín vivo',
    text: 'Una galería abierta de atmósferas, materiales vegetales y momentos del jardín.',
    rows: [
      {
        speed: 'slow',
        images: [
          { src: './assets/images/image1.webp', size: 'wide', crop: 'crop-a' },
          { src: './assets/images/image2.webp', size: 'portrait', crop: 'crop-b' },
          { src: './assets/images/image3.webp', size: 'square', crop: 'crop-c' },
          { src: './assets/images/image4.webp', size: 'feature', crop: 'crop-d' },
          { src: './assets/images/image5.webp', size: 'portrait', crop: 'crop-e' },
          { src: './assets/images/image6.webp', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/image7.webp', size: 'square', crop: 'crop-a' },
          { src: './assets/images/image8.webp', size: 'wide', crop: 'crop-b' },
          { src: './assets/images/image9.webp', size: 'portrait', crop: 'crop-c' },
          { src: './assets/images/image10.webp', size: 'feature', crop: 'crop-d' },
          { src: './assets/images/image11.webp', size: 'square', crop: 'crop-e' },
          { src: './assets/images/image12.webp', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/image13.webp', size: 'portrait', crop: 'crop-a' },
          { src: './assets/images/image14.webp', size: 'wide', crop: 'crop-b' },
          { src: './assets/images/image15.webp', size: 'square', crop: 'crop-c' },
          { src: './assets/images/image16.webp', size: 'feature', crop: 'crop-d' },
          { src: './assets/images/image17.webp', size: 'portrait', crop: 'crop-e' },
          { src: './assets/images/image18.webp', size: 'square', crop: 'crop-f' },
          { src: './assets/images/image19.webp', size: 'wide', crop: 'crop-a' },
        ],
      },
      {
        speed: 'medium',
        images: [
          { src: './assets/images/image20.webp', size: 'square', crop: 'crop-e' },
          { src: './assets/images/image21.webp', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/image22.webp', size: 'portrait', crop: 'crop-a' },
          { src: './assets/images/image23.webp', size: 'feature', crop: 'crop-b' },
          { src: './assets/images/image24.webp', size: 'square', crop: 'crop-c' },
          { src: './assets/images/image25.webp', size: 'wide', crop: 'crop-d' },
          { src: './assets/images/image26.webp', size: 'portrait', crop: 'crop-e' },
          { src: './assets/images/image27.webp', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/image28.webp', size: 'square', crop: 'crop-a' },
          { src: './assets/images/image29.webp', size: 'feature', crop: 'crop-b' },
          { src: './assets/images/image30.webp', size: 'portrait', crop: 'crop-c' },
          { src: './assets/images/image31.webp', size: 'wide', crop: 'crop-d' },
          { src: './assets/images/image32.webp', size: 'square', crop: 'crop-e' },
          { src: './assets/images/image33.webp', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/image34.webp', size: 'portrait', crop: 'crop-a' },
          { src: './assets/images/image35.webp', size: 'feature', crop: 'crop-b' },
          { src: './assets/images/image36.webp', size: 'square', crop: 'crop-c' },
          { src: './assets/images/image37.webp', size: 'wide', crop: 'crop-d' },
          { src: './assets/images/image38.webp', size: 'portrait', crop: 'crop-e' },
        ],
      },
      {
        speed: 'fast',
        images: [
          { src: './assets/images/image39.webp', size: 'portrait', crop: 'crop-d' },
          { src: './assets/images/image40.webp', size: 'feature', crop: 'crop-e' },
          { src: './assets/images/image41.webp', size: 'square', crop: 'crop-b' },
          { src: './assets/images/image42.webp', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/image43.webp', size: 'portrait', crop: 'crop-a' },
          { src: './assets/images/image44.webp', size: 'square', crop: 'crop-c' },
          { src: './assets/images/image45.webp', size: 'wide', crop: 'crop-d' },
          { src: './assets/images/image46.webp', size: 'feature', crop: 'crop-e' },
          { src: './assets/images/image47.webp', size: 'portrait', crop: 'crop-f' },
          { src: './assets/images/image48.webp', size: 'wide', crop: 'crop-a' },
          { src: './assets/images/image49.webp', size: 'square', crop: 'crop-b' },
          { src: './assets/images/image50.webp', size: 'wide', crop: 'crop-c' },
          { src: './assets/images/image51.webp', size: 'portrait', crop: 'crop-d' },
          { src: './assets/images/image52.webp', size: 'feature', crop: 'crop-e' },
        ],
      },
    ],
  },
  cta: {
    eyebrow: 'Contacto',
    title: 'Diseñemos tu jardín',
    text: 'Contanos sobre tu espacio y coordinamos una primera conversación.',
    action: 'Agendar consulta',
  },
  footer: {
    tagline: 'habitar tu naturaleza',
    areas: 'Punta del Este · La Barra · Manantiales · José Ignacio',
  },
};

window.SILVESTRA_CONTENT = SILVESTRA_CONTENT;
