const SILVESTRA_CONTENT = {
  assets: {
    logoColor: 'assets/logo-color-trim.png',
    logoCream: 'assets/logo-cream-trim.png',
    heroImage: './assets/hero.jpg',
  },
  contact: {
    email: 'hola@silvestra.uy',
    instagram: 'https://www.instagram.com/silvestra.paisajismo',
    instagramLabel: '@silvestra.paisajismo',
    phoneLabel: '097 236 903',
    phoneUrl: 'tel:+59897236903',
    whatsapp: 'https://wa.me/59897236903',
  },
  nav: [
    { href: '#filosofia', label: 'Filosofía' },
    { href: '#servicios', label: 'Servicios' },
    { href: '#planos', label: 'Planos' },
    { href: '#portfolio', label: 'Portfolio' },
    { href: '#contacto', label: 'Contacto' },
  ],
  hero: {
    eyebrow: 'Diseño y construcción de jardines · Punta del Este',
    title: 'habitar tu naturaleza',
    text: 'Paisajismo naturalista donde la estética del diseño y la vida silvestre crecen juntas.',
  },
  filosofia: {
    eyebrow: 'Nuestra filosofía',
    title: 'Lo silvestre también se diseña: jardines libres, vivos y en equilibrio.',
    accent: 'silvestre',
    text: 'Silvestra nace de esa idea: co-crear espacios con la naturaleza, no sobre ella. Jardines que despiertan en quienes los habitan la sensación de libertad, liviandad y sintonía con todo lo vivo que nos rodea.',
    pillars: [
      {
        number: '01',
        title: 'Co-crear, no controlar',
        text: 'Trabajamos con los procesos naturales, no sobre ellos. Plantas nativas combinadas con exóticas no invasoras, en diálogo con el monte costero, las dunas y la laguna.',
      },
      {
        number: '02',
        title: 'Refugio para la vida',
        text: 'Cada jardín atrae polinizadores, alimenta aves y suma un grano de arena a la biodiversidad local. Un ecosistema vivo, no solo una decoración.',
      },
      {
        number: '03',
        title: 'Sin químicos',
        text: 'Solo abonos orgánicos. Fauna protegida, niños y mascotas seguros. Un jardín sano que se sostiene en el tiempo y madura con las estaciones.',
      },
    ],
  },
  servicios: {
    eyebrow: 'Servicios',
    title: 'Del concepto al jardín que perdura',
    items: [
      {
        title: 'Consulta inicial',
        text: 'Visita al sitio, diagnóstico y primera valoración para entender el lugar, sus posibilidades y el alcance del proyecto.',
      },
      {
        title: 'Proyecto completo',
        text: 'Moodboard, memoria descriptiva, planos a escala, detalles constructivos, listado de especies y guía de manejo.',
      },
      {
        title: 'Ejecución y dirección de obra',
        text: 'Coordinación de equipo y dirección en obra. Hardscape incluido: decks, estanques, fogones y áreas de agua.',
      },
      {
        title: 'Seguimiento post-instalación',
        text: 'Visitas de puesta a punto durante el primer año para acompañar el arraigo y evolución del jardín.',
      },
    ],
  },
  proceso: {
    eyebrow: 'El proceso',
    title: 'Un camino claro, paso a paso',
    steps: [
      { number: '1', title: 'Consulta', text: 'Visita y diagnóstico del sitio.' },
      { number: '2', title: 'Moodboard', text: 'Propuesta conceptual y memoria.' },
      { number: '3', title: 'Proyecto', text: 'Planos, detalles y especies.' },
      { number: '4', title: 'Obra', text: 'Ejecución y dirección con hardscape.' },
      { number: '5', title: 'Seguimiento', text: 'Puesta a punto durante el año 1.' },
    ],
  },
  planos: {
    eyebrow: 'Planos y proceso creativo',
    title: 'Del trazo inicial a una lectura clara del jardín',
    text: 'Antes de construir, traducimos el lugar en capas: recorridos, especies, materialidades y atmósferas. Los planos y representaciones permiten visualizar decisiones y ajustar el proyecto con precisión.',
    images: [
      { src: './assets/planos/plano entero.jpg', label: 'Plano general', size: 'large' },
      { src: './assets/planos/zonificacion.jpg', label: 'Zonificación', size: 'medium' },
      { src: './assets/planos/especies.jpg', label: 'Especies', size: 'tall' },
      { src: './assets/planos/plano reserva.jpg', label: 'Reserva', size: 'medium' },
      { src: './assets/planos/plano villa.jpg', label: 'Villa', size: 'wide' },
      { src: './assets/planos/plantac.jpg', label: 'Plantación', size: 'small' },
      { src: './assets/planos/plantacion2.jpg', label: 'Plantación', size: 'medium' },
      { src: './assets/planos/aves estaciones.jpg', label: 'Aves y estaciones', size: 'wide' },
      { src: './assets/planos/axo.jpg', label: 'Representación', size: 'tall' },
      { src: './assets/planos/balcon alzado1.jpg', label: 'Alzado', size: 'medium' },
      { src: './assets/planos/pergola.jpg', label: 'Pérgola', size: 'small' },
      { src: './assets/planos/perspe cafe2.jpg', label: 'Perspectiva', size: 'small' },
      { src: './assets/planos/perspectiva4.jpg', label: 'Perspectiva', size: 'medium' },
      { src: './assets/planos/prader2.jpg', label: 'Pradera', size: 'small' },
      { src: './assets/planos/prader3.jpg', label: 'Pradera', size: 'medium' },
      { src: './assets/planos/pradera.jpg', label: 'Pradera', size: 'small' },
      { src: './assets/planos/rep.jpg', label: 'Representación', size: 'small' },
      { src: './assets/planos/repee.jpg', label: 'Representación', size: 'small' },
      { src: './assets/planos/repre.jpg', label: 'Representación', size: 'medium' },
      { src: './assets/planos/Ingreso2.jpg', label: 'Ingreso', size: 'small' },
    ],
    steps: [
      'Relevamiento del terreno y su entorno.',
      'Moodboard de atmósfera, materialidad y especies.',
      'Planos de implantación, canteros y recorridos.',
      'Representaciones para visualizar escala y experiencia.',
    ],
  },
  portfolio: {
    eyebrow: 'Portfolio',
    title: 'Texturas de jardín vivo',
    text: 'Una galería abierta de atmósferas, materiales vegetales y momentos del jardín.',
    rows: [
      {
        direction: 'left',
        speed: 'slow',
        images: [
          { src: './assets/images/imagen1.jpg', size: 'wide', crop: 'crop-a' },
          { src: './assets/images/imagen2.jpg', size: 'portrait', crop: 'crop-b' },
          { src: './assets/images/imagen3.jpg', size: 'square', crop: 'crop-c' },
          { src: './assets/images/imagen4.jpg', size: 'feature', crop: 'crop-d' },
          { src: './assets/images/imagen5.jpg', size: 'portrait', crop: 'crop-e' },
          { src: './assets/images/imagen6.jpg', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/imagen7.jpg', size: 'square', crop: 'crop-a' },
          { src: './assets/images/imagen8.jpg', size: 'wide', crop: 'crop-b' },
          { src: './assets/images/imagen9.jpg', size: 'portrait', crop: 'crop-c' },
          { src: './assets/images/imagen10.jpg', size: 'feature', crop: 'crop-d' },
          { src: './assets/images/imagen11.jpg', size: 'square', crop: 'crop-e' },
          { src: './assets/images/imagen12.jpg', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/imagen13.jpg', size: 'portrait', crop: 'crop-a' },
          { src: './assets/images/imagen14.jpg', size: 'wide', crop: 'crop-b' },
          { src: './assets/images/imagen15.jpg', size: 'square', crop: 'crop-c' },
          { src: './assets/images/imagen16.jpg', size: 'feature', crop: 'crop-d' },
          { src: './assets/images/imagen17.jpg', size: 'portrait', crop: 'crop-e' },
          { src: './assets/images/imagen18.jpg', size: 'square', crop: 'crop-f' },
          { src: './assets/images/imagen19.jpg', size: 'wide', crop: 'crop-a' },
        ],
      },
      {
        direction: 'right',
        speed: 'medium',
        images: [
          { src: './assets/images/imagen20.jpg', size: 'square', crop: 'crop-e' },
          { src: './assets/images/imagen21.jpg', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/imagen22.jpg', size: 'portrait', crop: 'crop-a' },
          { src: './assets/images/imagen23.jpg', size: 'feature', crop: 'crop-b' },
          { src: './assets/images/imagen24.jpg', size: 'square', crop: 'crop-c' },
          { src: './assets/images/imagen25.jpg', size: 'wide', crop: 'crop-d' },
          { src: './assets/images/imagen26.jpg', size: 'portrait', crop: 'crop-e' },
          { src: './assets/images/imagen27.jpg', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/imagen28.jpg', size: 'square', crop: 'crop-a' },
          { src: './assets/images/imagen29.jpg', size: 'feature', crop: 'crop-b' },
          { src: './assets/images/imagen30.jpg', size: 'portrait', crop: 'crop-c' },
          { src: './assets/images/imagen31.jpg', size: 'wide', crop: 'crop-d' },
          { src: './assets/images/imagen32.jpg', size: 'square', crop: 'crop-e' },
          { src: './assets/images/imagen33.jpg', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/imagen34.jpg', size: 'portrait', crop: 'crop-a' },
          { src: './assets/images/imagen35.jpg', size: 'feature', crop: 'crop-b' },
          { src: './assets/images/imagen36.jpg', size: 'square', crop: 'crop-c' },
          { src: './assets/images/imagen37.jpg', size: 'wide', crop: 'crop-d' },
          { src: './assets/images/imagen38.jpg', size: 'portrait', crop: 'crop-e' },
        ],
      },
      {
        direction: 'left',
        speed: 'fast',
        images: [
          { src: './assets/images/imagen39.jpg', size: 'portrait', crop: 'crop-d' },
          { src: './assets/images/imagen40.jpg', size: 'feature', crop: 'crop-e' },
          { src: './assets/images/imagen41.jpg', size: 'square', crop: 'crop-b' },
          { src: './assets/images/imagen42.jpg', size: 'wide', crop: 'crop-f' },
          { src: './assets/images/imagen43.jpg', size: 'portrait', crop: 'crop-a' },
          { src: './assets/images/imagen44.jpg', size: 'square', crop: 'crop-c' },
          { src: './assets/images/imagen45.jpg', size: 'wide', crop: 'crop-d' },
          { src: './assets/images/imagen46.jpg', size: 'feature', crop: 'crop-e' },
          { src: './assets/images/imagen47.jpg', size: 'portrait', crop: 'crop-f' },
          { src: './assets/images/imagen48.jpg', size: 'wide', crop: 'crop-a' },
          { src: './assets/images/imagen49.jpg', size: 'square', crop: 'crop-b' },
          { src: './assets/images/imagen50.jpg', size: 'wide', crop: 'crop-c' },
          { src: './assets/images/imagen51.jpg', size: 'portrait', crop: 'crop-d' },
          { src: './assets/images/imagen52.jpg', size: 'feature', crop: 'crop-e' },
          { src: './assets/images/imagen53.jpg', size: 'square', crop: 'crop-f' },
          { src: './assets/images/imagen54.jpg', size: 'wide', crop: 'crop-a' },
          { src: './assets/images/imagen55.jpg', size: 'portrait', crop: 'crop-b' },
          { src: './assets/images/imagen56.jpg', size: 'wide', crop: 'crop-c' },
        ],
      },
    ],
  },
  cta: {
    eyebrow: 'Contacto',
    title: 'Diseñemos tu jardín',
    text: 'Contanos sobre tu espacio y coordinamos una primera conversación.',
    action: 'Agendar consulta',
  },
  footer: {
    tagline: 'habitar tu naturaleza',
    areas: 'Punta del Este · La Barra · Manantiales · José Ignacio',
  },
};

window.SILVESTRA_CONTENT = SILVESTRA_CONTENT;
