// Contenido visible del sitio. Para SEO de imagenes, cada entrada de
// `portfolio.rows[].images` acepta un campo `alt` con la descripcion de
// la foto; sin `alt` se cae a un texto generico (ver Portfolio en sections.jsx).
export const content = {
  assets: {
    logoColor: 'assets/logo-color-trim.png',
    logoCream: 'assets/logo-cream-trim.png',
    heroImage: './assets/hero.jpg',
  },
  contact: {
    email: 'hola@silvestra.uy',
    instagram: 'https://www.instagram.com/silvestra.paisajismo',
    instagramLabel: '@silvestra.paisajismo',
    phoneLabel: '097 236 903',
    phoneUrl: 'tel:+59897236903',
    whatsapp: 'https://wa.me/59897236903',
  },
  nav: [
    { href: '#filosofia', label: 'Filosofía' },
    { href: '#servicios', label: 'Servicios' },
    { href: '#planos', label: 'Planos' },
    { href: '#portfolio', label: 'Portfolio' },
    { href: '#contacto', label: 'Contacto' },
  ],
  hero: {
    // El eyebrow queda solo con las localidades: la propuesta de valor
    // paso al H1, que antes era unicamente el lema y no tenia keyword.
    eyebrow: 'Punta del Este · La Barra · Manantiales · José Ignacio',
    tagline: 'habitar tu naturaleza',
    taglineAccent: 'habitar',
    headline: 'Diseño y construcción de jardines naturalistas',
    text: 'Paisajismo que dialoga con la naturaleza, la estética del diseño y los procesos vivos.',
    imageAlt:
      'Cantero de gramíneas y flores violetas y amarillas junto a un sendero de piedra, en un jardín naturalista de la costa de Maldonado',
  },
  filosofia: {
    eyebrow: 'Nuestra filosofía',
    title: 'Lo silvestre también se diseña. Jardines libres, vivos y en equilibrio.',
    accent: 'silvestre',
    text: 'Silvestra surge del deseo de co-crear con la naturaleza. Concebimos jardines que respetan sus ritmos y potencian su esencia, espacios donde la vegetación, la luz y el tiempo dialogan en armonía. Lugares que inspiran libertad, serenidad y una conexión profunda con el mundo vivo que nos contiene.',
    pillars: [
      {
        number: '01',
        title: 'Diseñar con la naturaleza',
        text: 'Trabajamos con los procesos naturales respetando la dinámica propia de cada lugar. Combinamos especies nativas con exóticas no invasoras para crear paisajes que dialogan con el monte costero, las dunas y la laguna.',
      },
      {
        number: '02',
        title: 'Refugio para la vida',
        text: 'Cada jardín es un pequeño ecosistema en movimiento. Atrae polinizadores, ofrece alimento y refugio a las aves y contribuye a fortalecer la biodiversidad local. Más que un espacio ornamental, es un lugar donde la vida encuentra su lugar.',
      },
      {
        number: '03',
        title: 'Sin químicos, con equilibrio',
        text: 'Trabajamos con abonos orgánicos y prácticas respetuosas con el ambiente. Fauna protegida, niños y mascotas seguros. Un jardín sano que se sostiene en el tiempo y madura con las estaciones.',
      },
    ],
  },
  servicios: {
    eyebrow: 'Servicios',
    title: 'Del concepto al jardín que perdura',
    items: [
      {
        number: '01',
        title: 'Consulta inicial',
        text: 'Visita al sitio, diagnóstico y primera valoración para entender el lugar, sus posibilidades y el alcance del proyecto.',
      },
      {
        number: '02',
        title: 'Proyecto completo',
        text: 'Moodboard, memoria descriptiva, planos a escala, detalles constructivos, listado de especies y guía de manejo.',
      },
      {
        number: '03',
        title: 'Ejecución y dirección de obra',
        text: 'Coordinación de equipo y dirección en obra. Hardscape incluido: decks, estanques, fogones y áreas de agua.',
      },
      {
        number: '04',
        title: 'Seguimiento post-instalación',
        text: 'Visitas de puesta a punto durante el primer año para acompañar el arraigo y evolución del jardín.',
      },
    ],
  },
  planos: {
    eyebrow: 'Planos y proceso creativo',
    title: 'Del trazo inicial a una lectura clara del jardín',
    text: 'Antes de construir, traducimos el lugar en capas: recorridos, especies, materialidades y atmósferas. Los planos y representaciones permiten visualizar decisiones y ajustar el proyecto con precisión.',
    images: [
      { src: './assets/planos/alzado-cantero-maritimo.webp', label: 'Alzado cantero marítimo', size: 'medium' },
      { src: './assets/planos/axonometria.webp', label: 'Axonometría', size: 'tall' },
      { src: './assets/planos/cantero-tecnica-mano-alzada.webp', label: 'Cantero, técnica mano alzada', size: 'small' },
      { src: './assets/planos/chacra-vista-area-espejos-de-agua.webp', label: 'Chacra, vista aérea de espejos de agua', size: 'wide' },
      { src: './assets/planos/corte-area-para-teens.webp', label: 'Corte, área para teens', size: 'medium' },
      { src: './assets/planos/corte-lago-y-puente.webp', label: 'Corte, lago y puente', size: 'wide' },
      { src: './assets/planos/corte-tecnica-mano-alzada.webp', label: 'Corte, técnica mano alzada', size: 'small' },
      { src: './assets/planos/corte-y-vista-de-balcon.webp', label: 'Corte y vista de balcón', size: 'medium' },
      { src: './assets/planos/diseno-de-pergola.webp', label: 'Diseño de pérgola', size: 'small' },
      { src: './assets/planos/grafico-aves-por-estaciones-proyecto-en-laguna.webp', label: 'Gráfico de aves por estaciones, proyecto en laguna', size: 'wide' },
      { src: './assets/planos/listado-especies-para-chacra.webp', label: 'Listado de especies para chacra', size: 'tall' },
      { src: './assets/planos/monte-nativo-y-mirador.webp', label: 'Monte nativo y mirador', size: 'medium' },
      { src: './assets/planos/perspectiva-cafe-museo.webp', label: 'Perspectiva, café museo', size: 'small' },
      { src: './assets/planos/perspectiva-patio-museo.webp', label: 'Perspectiva, patio museo', size: 'medium' },
      { src: './assets/planos/plano-de-plantacion.webp', label: 'Plano de plantación', size: 'large' },
      { src: './assets/planos/plano-laguna.webp', label: 'Plano laguna', size: 'medium' },
      { src: './assets/planos/plano-plantacion.webp', label: 'Plano plantación', size: 'small' },
      { src: './assets/planos/plano-reserva.webp', label: 'Plano reserva', size: 'medium' },
      { src: './assets/planos/plano-villa.webp', label: 'Plano villa', size: 'wide' },
      { src: './assets/planos/pradera-intervenida.webp', label: 'Pradera intervenida', size: 'small' },
      { src: './assets/planos/zonificacion-para-chacra.webp', label: 'Zonificación para chacra', size: 'medium' },
    ],
    steps: [
      'Relevamiento del terreno y su entorno.',
      'Moodboard de atmósfera, materialidad y especies.',
      'Planos de implantación, canteros y recorridos.',
      'Representaciones para visualizar escala y experiencia.',
    ],
  },
  portfolio: {
    eyebrow: 'Portfolio',
    title: 'Texturas de jardín vivo',
    text: 'Una galería abierta de atmósferas, materiales vegetales y momentos del jardín.',
    rows: [
      {
        speed: 'slow',
        images: [
          {
            src: './assets/images/image1.webp',
            alt: 'Cantero de verbenas violetas, aquileas rosadas y margaritas al borde de un césped curvo, con pinos al fondo',
            size: 'wide',
            crop: 'crop-a',
          },
          {
            src: './assets/images/image2.webp',
            alt: 'Pato silvestre en el borde de una piscina, con cortaderas y una palmera detrás',
            size: 'portrait',
            crop: 'crop-b',
          },
          {
            src: './assets/images/image3.webp',
            alt: 'Césped amplio bordeado con acero corten, salvias y buxus junto a una casa blanca',
            size: 'square',
            crop: 'crop-c',
          },
          {
            src: './assets/images/image4.webp',
            alt: 'Cantero de gramíneas y gomphrenas fucsias sobre mulch de corteza, frente a una casa de madera y vidrio',
            size: 'feature',
            crop: 'crop-d',
          },
          {
            src: './assets/images/image5.webp',
            alt: 'Jardín xerófilo bajo pérgola: cactus columnares, dasylirion y agaves sobre grava blanca',
            size: 'portrait',
            crop: 'crop-e',
          },
          {
            src: './assets/images/image6.webp',
            alt: 'Dalia rosada en flor sostenida en la mano, con más dalias amarillas y blancas detrás',
            size: 'wide',
            crop: 'crop-f',
          },
          {
            src: './assets/images/image7.webp',
            alt: 'Aquileas rosadas y amarillas alrededor de un bebedero de metal galvanizado',
            size: 'square',
            crop: 'crop-a',
          },
          {
            src: './assets/images/image8.webp',
            alt: 'Borde de piscina con gramíneas, salvias violetas y una strelitzia en maceta',
            size: 'wide',
            crop: 'crop-b',
          },
          {
            src: './assets/images/image9.webp',
            alt: 'Obelisco de hierro oxidado entre rosas y herbáceas, con borde de acero corten',
            size: 'portrait',
            crop: 'crop-c',
          },
          {
            src: './assets/images/image10.webp',
            alt: 'Flor de banano y racimo de bananas verdes entre hojas grandes',
            size: 'feature',
            crop: 'crop-d',
          },
          {
            src: './assets/images/image11.webp',
            alt: 'Cardos ornamentales en flor junto a una piscina con reposeras rayadas',
            size: 'square',
            crop: 'crop-e',
          },
          {
            src: './assets/images/image12.webp',
            alt: 'Gramíneas plumosas y flores violetas en un jardín con sillas blancas y pinos altos',
            size: 'wide',
            crop: 'crop-f',
          },
          {
            src: './assets/images/image13.webp',
            alt: 'Estanque circular de piedra con camalotes en flor, rodeado de cubresuelos y lavanda',
            size: 'portrait',
            crop: 'crop-a',
          },
          {
            src: './assets/images/image14.webp',
            alt: 'Cuenco bajo con echeverias y suculentas, entre verbenas rosadas y cosmos',
            size: 'wide',
            crop: 'crop-b',
          },
          {
            src: './assets/images/image15.webp',
            alt: 'Pradera florida de margaritas, viborera azul y lavanda frente a una casa blanca moderna',
            size: 'square',
            crop: 'crop-c',
          },
          {
            src: './assets/images/image16.webp',
            alt: 'Arbusto de flores lilas en primer plano, con césped, pasarela de losas y pérgola detrás',
            size: 'feature',
            crop: 'crop-d',
          },
          {
            src: './assets/images/image17.webp',
            alt: 'Cantero de orejas de elefante y filodendros contra un muro de ladrillo blanco',
            size: 'portrait',
            crop: 'crop-e',
          },
          {
            src: './assets/images/image18.webp',
            alt: 'Jardín con árboles añosos, agapantos y flores amarillas, con una casa de tejas al fondo',
            size: 'square',
            crop: 'crop-f',
          },
          {
            src: './assets/images/image19.webp',
            alt: 'Borde de cantero con aquileas blancas, salvias violetas y cosmos rosados sobre césped',
            size: 'wide',
            crop: 'crop-a',
          },
        ],
      },
      {
        speed: 'medium',
        images: [
          {
            src: './assets/images/image20.webp',
            alt: 'Cantero de verbenas rosadas y salvias violetas al borde de una terraza de losas',
            size: 'square',
            crop: 'crop-e',
          },
          {
            src: './assets/images/image21.webp',
            alt: 'Golden retriever al borde de una piscina, con un cantero de arbustos y flores detrás',
            size: 'wide',
            crop: 'crop-f',
          },
          {
            src: './assets/images/image22.webp',
            alt: 'Vista aérea de un jardín recién plantado con palmeras jóvenes, sendero de laja y deck de madera',
            size: 'portrait',
            crop: 'crop-a',
          },
          {
            src: './assets/images/image23.webp',
            alt: 'Deck de madera con maceteros negros y monte de eucaliptos, visto desde el interior',
            size: 'feature',
            crop: 'crop-b',
          },
          {
            src: './assets/images/image24.webp',
            alt: 'Jardinera elevada con gramíneas y agaves en la terraza de una casa de madera entre pinos',
            size: 'square',
            crop: 'crop-c',
          },
          {
            src: './assets/images/image25.webp',
            alt: 'Dos agaves en macetas negras flanqueando la puerta de madera de una casa',
            size: 'wide',
            crop: 'crop-d',
          },
          {
            src: './assets/images/image26.webp',
            alt: 'Salvias violetas y gomphrenas rosadas en un cantero con borde corten junto a una casa de madera',
            size: 'portrait',
            crop: 'crop-e',
          },
          {
            src: './assets/images/image27.webp',
            alt: 'Cantero de sombra con monsteras y filodendros sobre mulch de corteza, contra una pared de madera',
            size: 'wide',
            crop: 'crop-f',
          },
          {
            src: './assets/images/image28.webp',
            alt: 'Cantero de grava con gramíneas plumosas y banquetas de tronco, con borde de acero corten',
            size: 'square',
            crop: 'crop-a',
          },
          {
            src: './assets/images/image29.webp',
            alt: 'Mandarinas maduras en la mano, en una huerta de cítricos con jardineras de acero corten',
            size: 'feature',
            crop: 'crop-b',
          },
          {
            src: './assets/images/image30.webp',
            alt: 'Jardineras circulares de acero corten con kale y aromáticas, junto a un cerco de madera',
            size: 'portrait',
            crop: 'crop-c',
          },
          {
            src: './assets/images/image31.webp',
            alt: 'Limonero con frutos y jardineras corten con salvia y albahaca, frente a una casa de madera',
            size: 'wide',
            crop: 'crop-d',
          },
          {
            src: './assets/images/image32.webp',
            alt: 'Dos perros salchicha junto a un cantero de gramíneas y flores rosadas con borde corten',
            size: 'square',
            crop: 'crop-e',
          },
          {
            src: './assets/images/image33.webp',
            alt: 'Margaritas amarillas y salicaria rosada entre gramíneas plumosas',
            size: 'wide',
            crop: 'crop-f',
          },
          {
            src: './assets/images/image34.webp',
            alt: 'Lirios de hoja azulada, gramíneas y salicaria rosada junto a un sendero de grava',
            size: 'portrait',
            crop: 'crop-a',
          },
          {
            src: './assets/images/image35.webp',
            alt: 'Gramíneas, salicarias rosadas y margaritas amarillas bajo pinos y palmeras',
            size: 'feature',
            crop: 'crop-b',
          },
          {
            src: './assets/images/image36.webp',
            alt: 'Dedaleras rosadas y blancas vistas desde una ventana interior, con un bebedero en el césped',
            size: 'square',
            crop: 'crop-c',
          },
          {
            src: './assets/images/image37.webp',
            alt: 'Jardinera de madera con flores blancas y celestes al borde de un espejo de agua',
            size: 'wide',
            crop: 'crop-d',
          },
          {
            src: './assets/images/image38.webp',
            alt: 'Pradera de salicarias y margaritas amarillas frente a una piscina con reposeras y palmera',
            size: 'portrait',
            crop: 'crop-e',
          },
        ],
      },
      {
        speed: 'fast',
        images: [
          {
            src: './assets/images/image39.webp',
            alt: 'Aquileas coral, salvias violetas y margaritas contra un cerco cubierto de enredaderas',
            size: 'portrait',
            crop: 'crop-d',
          },
          {
            src: './assets/images/image40.webp',
            alt: 'Margaritas blancas y penstemon rojo junto a una casa blanca, con borde de acero corten',
            size: 'feature',
            crop: 'crop-e',
          },
          {
            src: './assets/images/image41.webp',
            alt: 'Rosal trepador magenta sobre obelisco de hierro, con lirios amarillos y una abeja',
            size: 'square',
            crop: 'crop-b',
          },
          {
            src: './assets/images/image42.webp',
            alt: 'Flores blancas y gramíneas junto a un camino de grava, con palmeras pindó y pinos',
            size: 'wide',
            crop: 'crop-f',
          },
          {
            src: './assets/images/image43.webp',
            alt: 'Casa de madera con cantero de gramíneas y flores blancas, y un formio rojizo en primer plano',
            size: 'portrait',
            crop: 'crop-a',
          },
          {
            src: './assets/images/image44.webp',
            alt: 'Sendero curvo de grava hacia la entrada de una casa moderna, entre salvias y gramíneas',
            size: 'square',
            crop: 'crop-c',
          },
          {
            src: './assets/images/image45.webp',
            alt: 'Sauce crespo sobre un patio de grava con banquetas de tronco y borde de acero corten',
            size: 'wide',
            crop: 'crop-d',
          },
          {
            src: './assets/images/image46.webp',
            alt: 'Salvias de flor violeta oscura junto a una pasarela de piedra, con piscina y pinos al fondo',
            size: 'feature',
            crop: 'crop-e',
          },
          {
            src: './assets/images/image47.webp',
            alt: 'Piscina de borde oscuro en un jardín con salvias rojas y gramíneas, rodeada de pinos',
            size: 'portrait',
            crop: 'crop-f',
          },
          {
            src: './assets/images/image48.webp',
            alt: 'Escalera de piedra laja hacia una casa de madera, con agave y cantero de flores blancas',
            size: 'wide',
            crop: 'crop-a',
          },
          {
            src: './assets/images/image49.webp',
            alt: 'Dos sillas bajas de madera en un patio de grava, entre petunias blancas y flores rosadas',
            size: 'square',
            crop: 'crop-b',
          },
          {
            src: './assets/images/image50.webp',
            alt: 'Salvias violeta oscuro y stipa dorada junto a la puerta roja de una casa blanca',
            size: 'wide',
            crop: 'crop-c',
          },
          {
            src: './assets/images/image51.webp',
            alt: 'Ligularias de hojas redondas y filodendros contra una pared de madera clara',
            size: 'portrait',
            crop: 'crop-d',
          },
          {
            src: './assets/images/image52.webp',
            alt: 'Primer plano de stipa dorada entre verbenas rosadas y margaritas amarillas',
            size: 'feature',
            crop: 'crop-e',
          },
        ],
      },
    ],
  },
  cta: {
    eyebrow: 'Contacto',
    title: 'Diseñemos tu jardín',
    text: 'Contanos sobre tu espacio y coordinamos una primera conversación.',
    action: 'Agendar consulta',
  },
  footer: {
    tagline: 'habitar tu naturaleza',
    areas: 'Punta del Este · La Barra · Manantiales · José Ignacio',
    year: new Date().getFullYear(),
  },
};

export default content;
